### ISSUE TITLE
Quote not paid should not log errors on 0.15.0 with LndRestWallet backend

### ISSUE THREAD

**Issue by zeugmaster** [cashubtc/nutshell#392]
When using nutshell 0.15.0 with the LND rest backend to mint, the mint, while waiting for the invoice to be payed, outputs an error with complete trace in intervals of approx. 4 seconds until the invoice is payed.

```
2024-01-18 20:27:15.52 | INFO | 95.90.247.20:40803 - "POST /mint?hash=XL4gB5q3wgq9MIspP7iQrIm855Srj1FOoAYttXGd HTTP/1.1" 400
2024-01-18 20:27:19.50 | ERROR | cashu.mint.app:catch_exceptions:105 | Exception: quote not paid
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/cashu-HVJa0CJv-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 98, in receive
    return self.receive_nowait()
  File "/root/.cache/pypoetry/virtualenvs/cashu-HVJa0CJv-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/cashu-HVJa0CJv-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "/root/.cache/pypoetry/virtualenvs/cashu-HVJa0CJv-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/cashu/cashu/mint/app.py", line 90, in catch_exceptions
    return await call_next(request)
  File "/root/.cache/pypoetry/virtualenvs/cashu-HVJa0CJv-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/root/.cache/pypoetry/virtualenvs/cashu-HVJa0CJv-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/root/.cache/pypoetry/virtualenvs/cashu-HVJa0CJv-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/root/.cache/pypoetry/virtualenvs/cashu-HVJa0CJv-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/cashu-HVJa0CJv-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/cashu-HVJa0CJv-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/.cache/pypoetry/virtualenvs/cashu-HVJa0CJv-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/root/.cache/pypoetry/virtualenvs/cashu-HVJa0CJv-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/cashu-HVJa0CJv-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/cashu-HVJa0CJv-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/cashu-HVJa0CJv-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/root/.cache/pypoetry/virtualenvs/cashu-HVJa0CJv-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/root/.cache/pypoetry/virtualenvs/cashu-HVJa0CJv-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/root/cashu/cashu/mint/router_deprecated.py", line 185, in mint_deprecated
    promises = await ledger.mint(outputs=payload.outputs, quote_id=hash)
  File "/root/cashu/cashu/mint/ledger.py", line 407, in mint
    assert quote.paid, "quote not paid"
AssertionError: quote not paid
2024-01-18 20:27:19.50 | INFO | 95.90.247.20:40803 - "POST /mint?hash=XL4gB5q3wgq9MIspP7iQrIm855Srj1FOoAYttXGd HTTP/1.1" 400
2024-01-18 20:27:23.51 | INFO | 95.90.247.20:40803 - "POST /mint?hash=XL4gB5q3wgq9MIspP7iQrIm855Srj1FOoAYttXGd HTTP/1.1" 200
2024-01-18 20:38:08.37 | INFO | 95.90.247.20:40801 - "POST /checkfees HTTP/1.1" 200
2024-01-18 20:38:08.45 | INFO | 95.90.247.20:40801 - "POST /split HTTP/1.1" 200
2024-01-18 20:38:09.08 | ERROR | cashu.lightning.lndrest:get_payment_status:218 | payment isn't initiated
2024-01-18 20:38:09.09 | DEBUG | cashu.mint.ledger:melt:660 | Lightning: pay invoice lnbc100n1pj6nrp8pp54x47ey8nk6wu9hv0d88nnp4eaxp3r6ffgxgz33n6gnanqdd44uxscqpjsp5x2338s6g6n60s5rflyyngvkjg79tej7qc7dpaxgaeneq04xm7xxq9q7sqqqqqqqqqqqqqqqqqqqsqqqqqysgqdqqmqz9gxqyjw5qrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glcllezhk2zechxl5qqqqlgqqqqqeqqjqzxksnr87mmmfp387uyndkz4pe60h9gs3jc6rle6jfwlkaqrjfmmqkzv7dul0583m5wzqfuqzvk3an6qypyykw54r59yps26r0whmz9cqthqlgn
2024-01-18 20:38:18.49 | INFO | 195.211.77.140:50626 - "HEAD / HTTP/1.1" 404
2024-01-18 20:38:34.19 | DEBUG | cashu.mint.ledger:melt:664 | Melt status: True: preimage: 0c83737fe6b28d68ec0b946a8a3a2f9bb5f91df43c914288eca35fbc48d21f3f, fee: 1012 msat
2024-01-18 20:38:34.19 | DEBUG | cashu.mint.ledger:_generate_change_promises:256 | Lightning fee was: 2. User paid: 2. Returning difference: 0.

**Comment by callebtc** [comment]
This error is ok but I agree, it's a bit too verbose to give a full stack trace here. It just means that the invoice has not been paid yet. Will adjust this to a normal error message instead of an exception.
