### ISSUE TITLE
Won't install on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by Impa10r** [cashubtc/nutshell#533]
Followed the manual up to this error:

```
ubuntu@primary:~/cashu$ poetry install
Installing dependencies from lock file

Package operations: 21 installs, 0 updates, 0 removals

  - Installing coincurve (18.0.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel

  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-cpython-312
  creating build/lib.linux-x86_64-cpython-312/coincurve
  copying coincurve/flags.py -> build/lib.linux-x86_64-cpython-312/coincurve
  copying coincurve/context.py -> build/lib.linux-x86_64-cpython-312/coincurve
  copying coincurve/_windows_libsecp256k1.py -> build/lib.linux-x86_64-cpython-312/coincurve
  copying coincurve/ecdsa.py -> build/lib.linux-x86_64-cpython-312/coincurve
  copying coincurve/__init__.py -> build/lib.linux-x86_64-cpython-312/coincurve
  copying coincurve/types.py -> build/lib.linux-x86_64-cpython-312/coincurve
  copying coincurve/keys.py -> build/lib.linux-x86_64-cpython-312/coincurve
  copying coincurve/utils.py -> build/lib.linux-x86_64-cpython-312/coincurve
  copying coincurve/py.typed -> build/lib.linux-x86_64-cpython-312/coincurve
  running build_clib
  /tmp/tmpl52q3wc_/coincurve-18.0.0/libsecp256k1/autogen.sh: 3: autoreconf: not found
  Traceback (most recent call last):
    File "/home/ubuntu/.local/share/pypoetry/venv/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
      main()
    File "/home/ubuntu/.local/share/pypoetry/venv/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/ubuntu/.local/share/pypoetry/venv/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 271, in build_wheel
      return _build_backend().build_wheel(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmp5h5s7ucu/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 410, in build_wheel
      return self._build_with_temp_dir(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmp5h5s7ucu/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/tmp5h5s7ucu/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
      super().run_setup(setup_script=setup_script)
    File "/tmp/tmp5h5s7ucu/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 266, in <module>
    File "/tmp/tmp5h5s7ucu/.venv/lib/python3.12/site-packages/setuptools/__init__.py", line 104, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmp5h5s7ucu/.venv/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "/tmp/tmp5h5s7ucu/.venv/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
      dist.run_commands()
    File "/tmp/tmp5h5s7ucu/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/tmp/tmp5h5s7ucu/.venv/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
      super().run_command(command)
    File "/tmp/tmp5h5s7ucu/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "<string>", line 97, in run
    File "/tmp/tmp5h5s7ucu/.venv/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 368, in run
      self.run_command("build")
    File "/tmp/tmp5h5s7ucu/.venv/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
      self.distribution.run_command(command)
    File "/tmp/tmp5h5s7ucu/.venv/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
      super().run_command(command)
    File "/tmp/tmp5h5s7ucu/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/tmp5h5s7ucu/.venv/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 132, in run
      self.run_command(cmd_name)
    File "/tmp/tmp5h5s7ucu/.venv/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
      self.distribution.run_command(command)
    File "/tmp/tmp5h5s7ucu/.venv/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
      super().run_command(command)
    File "/tmp/tmp5h5s7ucu/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "<string>", line 154, in run
    File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/tmp/tmpl52q3wc_/coincurve-18.0.0/libsecp256k1/autogen.sh']' returned non-zero exit status 127.


  at ~/.local/share/pypoetry/venv/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
      160│
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│
      163│             if error is not None:
    → 164│                 raise error from None
      165│
      166│             return path
      167│
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with coincurve (18.0.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "coincurve (==18.0.0)"'.

```

**Comment by Impa10r** [comment]
Fixed with:
```
sudo apt-get install autoconf
sudo apt-get install libtool
```
