### ISSUE TITLE
ERROR: AttributeError: 'NoneType' object has no attribute 'error_message' when running mint command

### ISSUE THREAD

**Issue by emtll** [cashubtc/nutshell#545]
AttributeError: 'NoneType' object has no attribute 'error_message' when running poetry run mint

I am getting the following error when trying to run the mint with the backend in USD via Strike:

2024-06-13 04:32:32.39 | INFO | cashu.mint.ledger:_startup_ledger:111 | Using BlinkWallet backend for method: 'bolt11' and unit: 'sat'
2024-06-13 04:32:33.43 | INFO | cashu.mint.ledger:_startup_ledger:123 | Backend balance: 552 sat
2024-06-13 04:32:33.43 | INFO | cashu.mint.ledger:_startup_ledger:111 | Using StrikeUSDWallet backend for method: 'bolt11' and unit: 'usd'
2024-06-13 04:32:33.72 | ERROR | Traceback (most recent call last):
  File "/home/admin/.cache/pypoetry/virtualenvs/cashu-ABqjf43N-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/home/admin/.cache/pypoetry/virtualenvs/cashu-ABqjf43N-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/home/admin/.cache/pypoetry/virtualenvs/cashu-ABqjf43N-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 654, in startup
    await handler()
  File "/home/admin/cashu/cashu/mint/app.py", line 105, in startup_mint
    await start_mint_init()
  File "/home/admin/cashu/cashu/mint/startup.py", line 88, in start_mint_init
    await ledger.startup_ledger()
  File "/home/admin/cashu/cashu/mint/ledger.py", line 98, in startup_ledger
    await self._startup_ledger()
  File "/home/admin/cashu/cashu/mint/ledger.py", line 116, in _startup_ledger
    if status.error_message:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'error_message'

2024-06-13 04:32:33.72 | ERROR | Application startup failed. Exiting.

.env:
MINT_DERIVATION_PATH_LIST=["m/0'/0'/0'", "m/0'/2'/0'"]
MINT_BACKEND_BOLT11_SAT=BlinkWallet
MINT_BACKEND_BOLT11_USD=StrikeUSDWallet

If I remove the USD backend, the mint runs normally. If I only remove the API key from Strike, the mint runs but the option to mint USD e-cash obviously doesn't work.

![image](https://github.com/cashubtc/nutshell/assets/125327891/efd25a95-51aa-433a-a6df-73d5adcb3723)

**Comment by callebtc** [comment]
Is this maybe because your Strike account does not support USD?

**Comment by pcwd** [comment]
Same error for me and my Strike account has a separate USD and btc balances.  And I can convert between lightning and usd in the wallet.

**Comment by emtll** [comment]
> Is this maybe because your Strike account does not support USD?

It supports, i can convert between ln and usd

**Comment by callebtc** [comment]
Fixed in #583. Please reopen if this problem persists.
