### ISSUE TITLE
pip install cashu in python venv failing on mac

### ISSUE THREAD

**Issue by Dayvvo** [cashubtc/nutshell#546]
pip install cashu runs for a while and fails with the following traceback 

```
Building wheels for collected packages: coincurve
  Building wheel for coincurve (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for coincurve (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [72 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-14.0-x86_64-cpython-312
      creating build/lib.macosx-14.0-x86_64-cpython-312/coincurve
      copying coincurve/_windows_libsecp256k1.py -> build/lib.macosx-14.0-x86_64-cpython-312/coincurve
      copying coincurve/flags.py -> build/lib.macosx-14.0-x86_64-cpython-312/coincurve
      copying coincurve/__init__.py -> build/lib.macosx-14.0-x86_64-cpython-312/coincurve
      copying coincurve/keys.py -> build/lib.macosx-14.0-x86_64-cpython-312/coincurve
      copying coincurve/types.py -> build/lib.macosx-14.0-x86_64-cpython-312/coincurve
      copying coincurve/context.py -> build/lib.macosx-14.0-x86_64-cpython-312/coincurve
      copying coincurve/utils.py -> build/lib.macosx-14.0-x86_64-cpython-312/coincurve
      copying coincurve/ecdsa.py -> build/lib.macosx-14.0-x86_64-cpython-312/coincurve
      copying coincurve/py.typed -> build/lib.macosx-14.0-x86_64-cpython-312/coincurve
      running build_clib
      Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.72/share/autoconf/Autom4te/FileUtils.pm line 299.
      autoreconf: error: aclocal failed with exit status: 2
      Traceback (most recent call last):
        File "/Users/mac/Documents/Work/bitcoin/cashuvenv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/mac/Documents/Work/bitcoin/cashuvenv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/mac/Documents/Work/bitcoin/cashuvenv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yw/f_ms07y17h9bcdq5g7swp2x80000gn/T/pip-build-env-prws6a_l/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 410, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yw/f_ms07y17h9bcdq5g7swp2x80000gn/T/pip-build-env-prws6a_l/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/yw/f_ms07y17h9bcdq5g7swp2x80000gn/T/pip-build-env-prws6a_l/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/yw/f_ms07y17h9bcdq5g7swp2x80000gn/T/pip-build-env-prws6a_l/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 266, in <module>
        File "/private/var/folders/yw/f_ms07y17h9bcdq5g7swp2x80000gn/T/pip-build-env-prws6a_l/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yw/f_ms07y17h9bcdq5g7swp2x80000gn/T/pip-build-env-prws6a_l/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yw/f_ms07y17h9bcdq5g7swp2x80000gn/T/pip-build-env-prws6a_l/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/private/var/folders/yw/f_ms07y17h9bcdq5g7swp2x80000gn/T/pip-build-env-prws6a_l/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/yw/f_ms07y17h9bcdq5g7swp2x80000gn/T/pip-build-env-prws6a_l/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 968, in run_command
          super().run_command(command)
        File "/private/var/folders/yw/f_ms07y17h9bcdq5g7swp2x80000gn/T/pip-build-env-prws6a_l/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 97, in run
        File "/private/var/folders/yw/f_ms07y17h9bcdq5g7swp2x80000gn/T/pip-build-env-prws6a_l/normal/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/private/var/folders/yw/f_ms07y17h9bcdq5g7swp2x80000gn/T/pip-build-env-prws6a_l/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/yw/f_ms07y17h9bcdq5g7swp2x80000gn/T/pip-build-env-prws6a_l/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 968, in run_command
          super().run_command(command)
        File "/private/var/folders/yw/f_ms07y17h9bcdq5g7swp2x80000gn/T/pip-build-env-prws6a_l/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/yw/f_ms07y17h9bcdq5g7swp2x80000gn/T/pip-build-env-prws6a_l/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/private/var/folders/yw/f_ms07y17h9bcdq5g7swp2x80000gn/T/pip-build-env-prws6a_l/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/yw/f_ms07y17h9bcdq5g7swp2x80000gn/T/pip-build-env-prws6a_l/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 968, in run_command
          super().run_command(command)
        File "/private/var/folders/yw/f_ms07y17h9bcdq5g7swp2x80000gn/T/pip-build-env-prws6a_l/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 154, in run
        File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/private/var/folders/yw/f_ms07y17h9bcdq5g7swp2x80000gn/T/pip-install-dsc4dzn3/coincurve_0df94ae4af4543b3bc0227d024a8e379/libsecp256k1/autogen.sh']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for coincurve
Failed to build coincurve
ERROR: Could not build wheels for coincurve, which is required to install pyproject.toml-based projects
```

**Steps I carried out**

- created a python virtual environment i.e python3 -m venv "venvname"
- pip install cashu

Environment:
Device: Macbook Pro 2018 2.9GHZ 6 Core intel-core 19
Operating system: MacOS Sonoma 14.5

**Comment by callebtc** [comment]
Can you successfully install from the repo using poetry?
